// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Homin Lee",
            "url": "https://github.com/suapapa",
            "email": "ff4500@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the service is healthy by verifying temporary directory access and active refs file readability",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/luggage": {
            "post": {
                "description": "Upload a file and get a unique key. The file will be automatically deleted after TTL expires (default: 3 minutes) if there are no active references.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "luggage"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Custom key (optional, auto-generated if not provided)",
                        "name": "key",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "MIME type (optional, auto-detected if not provided)",
                        "name": "mime",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Time to live in minutes (default: 3)",
                        "name": "ttl",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/luggage.SaveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (file required or size exceeds limit)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/luggage/{key}": {
            "get": {
                "description": "Retrieve a file using the key returned from upload. The file can be downloaded with original filename or viewed inline.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "luggage"
                ],
                "summary": "Get a file by key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set to 'true' to download with original filename",
                        "name": "download",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stat": {
            "get": {
                "description": "Get statistics about all stored files including total keys, total size, active references, and details for each key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stat"
                ],
                "summary": "Get statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/luggage.StatResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "luggage.KeyStat": {
            "type": "object",
            "properties": {
                "activeRefs": {
                    "type": "integer"
                },
                "directory": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "filename": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                }
            }
        },
        "luggage.SaveResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "luggage.StatResponse": {
            "type": "object",
            "properties": {
                "activeRefs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/luggage.KeyStat"
                    }
                },
                "totalKeys": {
                    "type": "integer"
                },
                "totalSize": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and API token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Concierge API",
	Description:      "A temporary file storage service with TTL support",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
